# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'bson_ext'
gem 'activemodel', '< 5'
gem 'mongo_mapper'
